"""empty message

Revision ID: 137c2ca5a2d9
Revises: 6d4f8eddd977
Create Date: 2019-08-21 19:06:26.244384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '137c2ca5a2d9'
down_revision = '6d4f8eddd977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_input', sa.Column('upload_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_input', 'upload_time')
    # ### end Alembic commands ###
