"""empty message

Revision ID: 446713a25bb0
Revises: 2c52a7c8e91c
Create Date: 2019-08-21 16:11:29.317175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '446713a25bb0'
down_revision = '2c52a7c8e91c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prediction', sa.Column('prediction_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prediction', 'prediction_time')
    # ### end Alembic commands ###
