"""empty message

Revision ID: 6d4f8eddd977
Revises: 7678aeea4c9c
Create Date: 2019-08-21 18:58:06.409275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d4f8eddd977'
down_revision = '7678aeea4c9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_input',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('weekday', sa.String(length=100), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('prediction', sa.Text(), nullable=True),
    sa.Column('prediction_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['persistent_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediction')
    op.drop_table('user_input')
    # ### end Alembic commands ###
