"""empty message

Revision ID: 7678aeea4c9c
Revises: 446713a25bb0
Create Date: 2019-08-21 18:56:15.386157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7678aeea4c9c'
down_revision = '446713a25bb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_input')
    op.drop_table('prediction')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prediction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('model_id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=True),
    sa.Column('prediction', sa.FLOAT(), nullable=True),
    sa.Column('prediction_time', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['persistent_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_input',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=200), nullable=True),
    sa.Column('weekday', sa.VARCHAR(length=100), nullable=True),
    sa.Column('day_of_month', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
