"""init models

Revision ID: b55cb028a4c9
Revises: 
Create Date: 2019-08-20 18:57:02.055263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b55cb028a4c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persistent_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('params', sa.String(length=200), nullable=True),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.Column('in_use', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('persistent_model')
    # ### end Alembic commands ###
